config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vehicles

  root 'vehicles#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :name, :year, :miles, :category, :price, :color, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Car Dealership</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lobster|Roboto' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="pull-right">
    <% if user_signed_in? %>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-warning" %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :make %><br>
    <%= f.text_field :make, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :year %><br>
    <%= f.number_field :year, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :miles %><br>
    <%= f.number_field :miles, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<div class="row">
    <% @vehicles.each do |vehicle| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-heading">
         <h3><%= vehicle.make %></h3>
         <h3><%= vehicle.name %></h3>
       </div>
       <div class="panel-body">
         <p>Year: <%= vehicle.year %></p>
         <p>Miles: <%= vehicle.miles %></p>
         <p><%= vehicle.category %></p>
         <p>$<%= vehicle.price %></p>
         <p>Color: <%= vehicle.color %></p>
         <% if vehicle.avatar_file_name != nil %>
         <%= image_tag vehicle.avatar.url(:medium), class: "img-responsive" %>
         <% end %>
         <div class="btn-group">
          <%= link_to 'Show', vehicle, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_vehicle_path(vehicle), class: "btn btn-success" %>
          <%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path, class: "btn btn-primary" %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @vehicle.miles %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vehicle.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<% if @vehicle.avatar_file_name != nil %>
  <%= image_tag @vehicle.avatar.url(:medium) %>
<% end %>
<br />

<%= link_to 'Edit', edit_vehicle_path(@vehicle), class: "btn btn-primary" %> |
<%= link_to 'Back', vehicles_path, class: "btn btn-primary" %>